services:
  synkro-sales-api:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    environment:
      HTTP_PORT: "8080"
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
    expose: ["8080"]
    networks: [platform]

networks:
  platform:
    external: true
